services:
  db:
    image: postgres
    container_name: base_fastapi_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5434:5432

    volumes:
      - postgres_data:/var/lib/postgresql


  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_WEB_PORT=1080
    ports:
      - 8080:1080
      - 1025:1025

    logging:
      driver: "json-file"
      options:
        max-size: "1m"

volumes:
  postgres_data: